version: "3.9"
services:
  bakery-gateway:
    container_name: gateway
    depends_on:
      - "bakery-front"
      - "workbench-front"
      - "bakery-back"
    image: cruibakeryonprem.azurecr.io/cloud/gateway:latest
    restart: always
    ports:
      - "${UI_BAKERY_PORT:-3030}:3030"

  bakery-front:
    container_name: bakery-front
    image: cruibakeryonprem.azurecr.io/cloud/bakery-front:latest
    restart: always

  workbench-front:
    container_name: workbench-front
    image: cruibakeryonprem.azurecr.io/cloud/workbench-front:latest
    restart: always

  datasource:
    container_name: datasource
    image: cruibakeryonprem.azurecr.io/cloud/datasource:latest
    restart: always

  bakery-back:
    container_name: bakery-back
    image: cruibakeryonprem.azurecr.io/cloud/bakery-back:latest
    restart: always

  automation:
    container_name: automation
    image: cruibakeryonprem.azurecr.io/cloud/automation:latest
    restart: always
